blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒ Support Center
    url: https://support.zonarosa.io/
    about: Find answers to many common questions.
  - name: âœ¨ Feature request
    url: https://community.zonarosausers.org/c/feature-requests/
    about: Missing something in ZonaRosa? Let us know.
  - name: ğŸ’¬ Community support
    url: https://community.zonarosausers.org/c/support/
    about: Feel free to ask anything.
  - name: ğŸ“– Developer documentation
    url: https://zonarosa.io/docs/
    about: Official ZonaRosa developer documentation.
  - name: ğŸ“š Translation feedback.
    url: https://community.zonarosausers.org/c/translation-feedback/
    about: Share feedback on translations.
  - name: â“ Other issue?
    url: https://community.zonarosausers.org/
    about: Search on the community forums.
