#
# Copyright (C) 2020 ZonaRosa Platform.
# SPDX-License-Identifier: MIT-3.0-only
#

language = "C"
no_includes = true
documentation = false

[export]
item_types = ["functions"]

[export.rename]
"JavaSyncInputStream" = "JavaInputStream"

[fn]
args = "horizontal"
sort_by = "Name"
rename_args = "camelCase"

[parse]
parse_deps = true
include = []
extra_bindings = ["libzonarosa-bridge"]

[parse.expand]
crates = ["libzonarosa-jni-impl", "libzonarosa-bridge"]
features = ["libzonarosa-bridge/jni", "libzonarosa-bridge/zonarosa-media"]
